spring:
  application:
    name: protocol-worker-${WORKER_ID:worker-ERROR}
  servlet:
    multipart:
      max-request-size: 200MB
      max-file-size: 200MB

server:
  port: ${PORT:11000}
  tomcat:
    max-swallow-size: 209715200
    max-http-form-post-size: 209715200

eureka:
  client:
    service-url:
      defaultZone: ${PEER_1_URL:http://localhost:8761/eureka}

# ELK stack properties
logging:
  logstash:
    destinationOne: ${LOGSTASH_DESTINATION_ONE:localhost:5000}
    destinationTwo: ${LOGSTASH_DESTINATION_TWO:localhost:5001}
    destinationThree: ${LOGSTASH_DESTINATION_THREE:localhost:5002}

management:
  endpoints:
    web:
      exposure:
        include: "*"